steps:
  # Fetch secrets from Secret Manager and write to environment variables
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        USERNAME=$(gcloud secrets versions access latest --secret=USERNAME)
        PASSWORD=$(gcloud secrets versions access latest --secret=PASSWORD)
        HUGGING_FACE_AUTH_KEY=$(gcloud secrets versions access latest --secret=HUGGING_FACE_AUTH_KEY)
        echo "USERNAME=$USERNAME" >> /workspace/.env
        echo "PASSWORD=$PASSWORD" >> /workspace/.env
        echo "HUGGING_FACE_AUTH_KEY=$HUGGING_FACE_AUTH_KEY" >> /workspace/.env

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app', '.']

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app']

  # Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy my-huggingface-web-app \
          --image us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars USERNAME=$USERNAME,PASSWORD=$PASSWORD,HUGGING_FACE_AUTH_KEY=$HUGGING_FACE_AUTH_KEY

logsBucket: 'app-demo-ai'

images:
  - 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app'
