steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app', '.']

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app']

  # Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'my-huggingface-web-app',
      '--image', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--set-env-vars',
      'USERNAME_SECRET=projects/your-project-id/secrets/username_secret_name/versions/latest,' +
      'PASSWORD_SECRET=projects/your-project-id/secrets/password_secret_name/versions/latest,' +
      'HUGGING_FACE_API_KEY_SECRET=projects/your-project-id/secrets/hugging_face_api_key_secret_name/versions/latest'
    ]

logsBucket: 'app-demo-ai'
images:
  - 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app'
