steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app', '.']

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app']

  # Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy my-huggingface-web-app \
          --image us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars USERNAME=$$USERNAME,PASSWORD=$$PASSWORD,HUGGING_FACE_AUTH_KEY=$$HUGGING_FACE_AUTH_KEY
    secretEnv: ['USERNAME', 'PASSWORD', 'HUGGING_FACE_AUTH_KEY']

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/USERNAME/versions/latest
    env: 'USERNAME'
  - versionName: projects/$PROJECT_ID/secrets/PASSWORD/versions/latest
    env: 'PASSWORD'
  - versionName: projects/$PROJECT_ID/secrets/HUGGING_FACE_AUTH_KEY/versions/latest
    env: 'HUGGING_FACE_AUTH_KEY'

logsBucket: 'app-demo-ai'

images:
  - 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app'
