steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app', '.']

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app']

  # Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'my-huggingface-web-app',
      '--image', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated',
      '--add-cloudsql-instances', 'my-money-428813:us-central1:mysql-db01', # Updated instance connection name
      '--set-env-vars', 'HUGGING_FACE_API_KEY=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,DB_USER=root,DB_PASSWORD=Sathi@1993,DB_NAME=demo-gen,INSTANCE_CONNECTION_NAME=my-money-428813:us-central1:mysql-db01'
    ]

logsBucket: 'app-demo-ai'

images:
  - 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app'
