steps:
  # Fetch secrets from Secret Manager and set them as substitutions
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Fetch Secrets
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        export USERNAME=$(gcloud secrets versions access latest --secret=USERNAME)
        export PASSWORD=$(gcloud secrets versions access latest --secret=PASSWORD)
        export HUGGING_FACE_AUTH_KEY=$(gcloud secrets versions access latest --secret=HUGGING_FACE_AUTH_KEY)
        echo "SUBSTITUTE_USERNAME=${USERNAME}" >> /workspace/env.list
        echo "SUBSTITUTE_PASSWORD=${PASSWORD}" >> /workspace/env.list
        echo "SUBSTITUTE_HUGGING_FACE_AUTH_KEY=${HUGGING_FACE_AUTH_KEY}" >> /workspace/env.list

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app', '.']

  # Push the Docker image to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app']

  # Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/env.list
        gcloud run deploy my-huggingface-web-app \
          --image us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars USERNAME=${SUBSTITUTE_USERNAME},PASSWORD=${SUBSTITUTE_PASSWORD},HUGGING_FACE_AUTH_KEY=${SUBSTITUTE_HUGGING_FACE_AUTH_KEY}

logsBucket: 'app-demo-ai'

images:
  - 'us-central1-docker.pkg.dev/my-money-428813/my-ai-app-test/my-huggingface-web-app'
